CREATE TABLE [dbo].[cfs_team_member_hist_dim] (
    [src_rctl_load_dttm]       DATETIME2 (7) NULL,
    [src_rctl_update_dttm]     DATETIME2 (7) NULL,
    [rctl_load_dttm]           DATETIME2 (7) NULL,
    [rctl_update_dttm]         DATETIME2 (7) NULL,
    [source_name]              VARCHAR (50)  NULL,
    [event_timestamp]          DATETIME2 (7) NULL,
    [team_member_key]          VARCHAR (36)  NULL,
    [valid_to_dttm]            DATETIME2 (7) NULL,
    [valid_from_dttm]          DATETIME2 (7) NULL,
    [valid_from_dttm_epoch]    BIGINT        NULL,
    [valid_to_dttm_epoch]      BIGINT        NULL,
    [first_name]               VARCHAR (50)  NULL,
    [middle_name_initial]      VARCHAR (50)  NULL,
    [last_name]                VARCHAR (50)  NULL,
    [initials]                 VARCHAR (10)  NULL,
    [suffix]                   VARCHAR (50)  NULL,
    [team_member_code]         VARCHAR (32)  NULL,
    [team_member_type]         VARCHAR (32)  NULL,
    [status]                   VARCHAR (32)  NULL,
    [national_provider_id]     VARCHAR (32)  NULL,
    [location_number]          VARCHAR (32)  NULL,
    [location_type]            VARCHAR (32)  NULL,
    [sso_user_id]              VARCHAR (32)  NULL,
    [email]                    VARCHAR (100) NULL,
    [work_phone]               VARCHAR (32)  NULL,
    [home_phone]               VARCHAR (32)  NULL,
    [position_code]            VARCHAR (32)  NULL,
    [idp_employee_type]        VARCHAR (32)  NULL,
    [idp_user_type]            VARCHAR (32)  NULL,
    [lastupdate_datetime]      DATETIME2 (7) NULL,
    [lastupdate_user_code]     VARCHAR (32)  NULL,
    [lastupdate_user_type]     VARCHAR (32)  NULL,
    [lastupdate_location_code] VARCHAR (32)  NULL,
    [lastupdate_location_type] VARCHAR (32)  NULL
)
WITH (CLUSTERED INDEX([team_member_key]), DISTRIBUTION = REPLICATE);

