CREATE TABLE [dbo].[sc_stock_movement_trx_fct] (
    [rctl_load_dttm]           DATETIME2 (7)   NULL,
    [rctl_update_dttm]         DATETIME2 (7)   NULL,
    [source_name]              VARCHAR (32)    NULL,
    [event_timestamp]          DATETIME2 (7)   NULL,
    [location_key]             VARCHAR (36)    NULL,
    [location_ref_timestamp]   DATETIME2 (7)   NULL,
    [location_code]            VARCHAR (32)    NULL,
    [location_type]            VARCHAR (32)    NULL,
    [location_timezone_id]     VARCHAR (32)    NULL,
    [product_key]              VARCHAR (32)    NULL,
    [product_ref_timestamp]    DATETIME2 (7)   NULL,
    [product_code]             VARCHAR (32)    NULL,
    [product_identifier_code]  VARCHAR (32)    NULL,
    [product_identifier_type]  VARCHAR (32)    NULL,
    [date_key]                 INT             NULL,
    [time_partition_key]       INT             NULL,
    [stock_movement_datetime]  DATETIME2 (7)   NULL,
    [current_quantity]         DECIMAL (18, 3) NULL,
    [previous_quantity]        DECIMAL (18, 3) NULL,
    [delta_quantity]           DECIMAL (18, 3) NULL,
    [operation_type]           VARCHAR (50)    NULL,
    [stock_movement_type]      VARCHAR (32)    NULL,
    [reason]                   VARCHAR (32)    NULL,
    [received_from_process]    VARCHAR (32)    NULL,
    [service_type]             VARCHAR (32)    NULL,
    [service_code]             VARCHAR (36)    NULL,
    [external_service_code]    VARCHAR (100)   NULL,
    [received_from_datetime]   DATETIME2 (7)   NULL,
    [src_rctl_load_dttm]       DATETIME2 (7)   NULL,
    [src_rctl_update_dttm]     DATETIME2 (7)   NULL,
    [lastupdate_timestamp]     DATETIME2 (7)   NULL,
    [lastupdate_user_code]     VARCHAR (32)    NULL,
    [lastupdate_user_type]     VARCHAR (32)    NULL,
    [lastupdate_location_code] VARCHAR (32)    NULL,
    [lastupdate_location_type] VARCHAR (32)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([location_key]), PARTITION([time_partition_key] RANGE RIGHT FOR VALUES (2018, 2019, 2020)));

