CREATE TABLE [dbo].[sc_supplier_history_dim] (
    [rctl_load_dttm]             DATETIME2 (7) NULL,
    [rctl_update_dttm]           DATETIME2 (7) NULL,
    [source_name]                VARCHAR (100) NULL,
    [event_produced_time]        DATETIME2 (7) NULL,
    [supplier_key]               VARCHAR (36)  NULL,
    [valid_from_dttm]            DATETIME2 (7) NULL,
    [valid_to_dttm]              DATETIME2 (7) NULL,
    [valid_from_dttm_epoch]      BIGINT        NULL,
    [valid_to_dttm_epoch]        BIGINT        NULL,
    [supplier_code]              VARCHAR (32)  NULL,
    [supplier_type]              VARCHAR (32)  NULL,
    [supplier_name]              VARCHAR (100) NULL,
    [supplier_application_code]  VARCHAR (32)  NULL,
    [supplier_status]            VARCHAR (32)  NULL,
    [supplier_short_name]        VARCHAR (50)  NULL,
    [address]                    VARCHAR (100) NULL,
    [city]                       VARCHAR (50)  NULL,
    [country]                    VARCHAR (50)  NULL,
    [state]                      VARCHAR (3)   NULL,
    [zipcode]                    VARCHAR (32)  NULL,
    [contact]                    VARCHAR (50)  NULL,
    [phone_number]               VARCHAR (32)  NULL,
    [fax_number]                 VARCHAR (32)  NULL,
    [license_number]             VARCHAR (32)  NULL,
    [license_type]               VARCHAR (32)  NULL,
    [trading_partner_id]         VARCHAR (32)  NULL,
    [item_routing_flag]          VARCHAR (50)  NULL,
    [default_ordering_qualifier] VARCHAR (50)  NULL,
    [auto_release_flag]          VARCHAR (50)  NULL,
    [manual_transaction]         VARCHAR (32)  NULL,
    [add_substitute_item]        VARCHAR (32)  NULL,
    [customer_number]            VARCHAR (32)  NULL,
    [supplier_lead_time]         INT           NULL,
    [minimum_order_quantity]     INT           NULL,
    [rx_controlled_drugs]        VARCHAR (5)   NULL,
    [delivery_type]              VARCHAR (32)  NULL,
    [purchasing_contact]         VARCHAR (50)  NULL,
    [supplier_establish_date]    DATETIME2 (7) NULL,
    [src_rctl_load_dttm]         DATETIME2 (7) NULL,
    [src_rctl_update_dttm]       DATETIME2 (7) NULL
)
WITH (CLUSTERED INDEX([supplier_key]), DISTRIBUTION = REPLICATE);

